/* WolfSSLPQCAuthenticationTest.java
 *
 * Copyright (C) 2006-2026 wolfSSL Inc.
 *
 * This file is part of wolfSSL.
 *
 * wolfSSL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * wolfSSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

package com.wolfssl.provider.jsse.test;

import java.util.List;
import java.util.Arrays;
import com.wolfssl.WolfSSL;
import com.wolfssl.WolfSSLCertificate;
import com.wolfssl.WolfSSLException;
import com.wolfssl.WolfSSLX509Name;
import com.wolfssl.provider.jsse.WolfSSLInternalVerifyCb;
import com.wolfssl.provider.jsse.WolfSSLProvider;
import com.wolfssl.provider.jsse.WolfSSLX509;
import com.wolfssl.test.TimedTestWatcher;
import com.wolfssl.test.WolfSSLTestCommon;
import java.math.BigInteger;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PublicKey;
import java.security.Security;
import java.time.Duration;
import java.time.Instant;
import java.util.Date;
import javax.net.ssl.ExtendedSSLSession;
import javax.net.ssl.KeyManager;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManager;
import org.junit.Assume;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestRule;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * Integration tests for ML-DSA (FIPS 204) X.509 cert authentication via
 * wolfJSSE TLS 1.3.
 *
 * Uses {@link WolfSSLPQCTestUtil}'s custom KeyManager helper, which loads PEM
 * certs and PKCS#8 DER keys directly without invoking JCE KeyFactory. This
 * makes the same test runnable on Java 8 (no ML-DSA in JEP 497) through
 * JDK 24+ alike. Cert verification is delegated to native wolfSSL via wolfJSSE.
 *
 * Skipped automatically when:
 *   - native wolfSSL was not built with --enable-mldsa, OR
 *   - TLS 1.3 is not compiled in, OR
 *   - the gen-mldsa-certs.sh script has not been run (no PQC PEM files
 *     under examples/certs/pqc/).
 */
public class WolfSSLPQCAuthenticationTest {

    private static final String PROVIDER = "wolfJSSE";
    private static final String APP_DATA = "PQC auth test";

    /* ML-DSA-87 (CNSA 2.0) cert paths.
     * Generated by examples/certs/gen-mldsa-certs.sh */
    private static final String SERVER_CERT =
        "examples/certs/pqc/server-mldsa87.pem";
    private static final String SERVER_KEY =
        "examples/certs/pqc/server-mldsa87-priv.pem";
    private static final String CLIENT_CERT =
        "examples/certs/pqc/client-mldsa87.pem";
    private static final String CLIENT_KEY =
        "examples/certs/pqc/client-mldsa87-priv.pem";
    private static final String ROOT_CERT =
        "examples/certs/pqc/root-mldsa87.pem";

    private static WolfSSLTestFactory tf;

    @Rule
    public TestRule testWatcher = TimedTestWatcher.create();

    @BeforeClass
    public static void setUp()
        throws NoSuchProviderException, WolfSSLException {

        System.out.println("WolfSSLPQCAuthentication Class");

        Security.insertProviderAt(new WolfSSLProvider(), 1);
        tf = new WolfSSLTestFactory();
    }

    /**
     * Common skip preconditions for every test in this class. Routes
     * through Assume so the TimedTestWatcher reports SKIP rather than
     * the test failing.
     */
    private void preconditions() {
        Assume.assumeTrue(WolfSSL.MLDSAEnabled() && WolfSSL.TLSv13Enabled());

        Assume.assumeTrue("PQC cert PEM missing; run gen-mldsa-certs.sh first",
            WolfSSLPQCTestUtil.pqcCertExists(ROOT_CERT));

        Assume.assumeTrue(WolfSSLPQCTestUtil.MLDSA_CERT_PARSING_SKIP_MSG,
            WolfSSLPQCTestUtil.nativeMlDsaCertParsingSupported());
    }

    /**
     * Server presents an ML-DSA-87 cert. Client trusts the matching root and
     * verifies. No client auth.
     */
    @Test
    public void testServerAuth_MLDSA87() throws Exception {

        preconditions();

        KeyManager[] serverKm = WolfSSLPQCTestUtil.keyManagerFromPem(
            "server-mldsa87", SERVER_CERT, SERVER_KEY, "ML-DSA-87");
        TrustManager[] clientTm =
            WolfSSLPQCTestUtil.trustManagerFromPem(ROOT_CERT);

        SSLContext serverCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            null, serverKm);
        SSLContext clientCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            clientTm, null);

        SSLEngine server = serverCtx.createSSLEngine();
        server.setUseClientMode(false);
        server.setNeedClientAuth(false);

        SSLEngine client = clientCtx.createSSLEngine(
            "wolfSSL ML-DSA test", 11111);
        client.setUseClientMode(true);

        int ret = tf.testConnection(server, client, null,
            new String[] { "TLSv1.3" }, APP_DATA);

        assertEquals("ML-DSA-87 server-auth handshake should succeed", 0, ret);
    }

    /**
     * Mutual auth: both server and client present ML-DSA-87 certs, each side
     * trusts the matching root.
     */
    @Test
    public void testMutualAuth_MLDSA87() throws Exception {

        preconditions();

        KeyManager[] serverKm = WolfSSLPQCTestUtil.keyManagerFromPem(
            "server-mldsa87", SERVER_CERT, SERVER_KEY, "ML-DSA-87");
        TrustManager[] serverTm =
            WolfSSLPQCTestUtil.trustManagerFromPem(ROOT_CERT);
        KeyManager[] clientKm = WolfSSLPQCTestUtil.keyManagerFromPem(
            "client-mldsa87", CLIENT_CERT, CLIENT_KEY, "ML-DSA-87");
        TrustManager[] clientTm =
            WolfSSLPQCTestUtil.trustManagerFromPem(ROOT_CERT);

        SSLContext serverCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            serverTm, serverKm);
        SSLContext clientCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            clientTm, clientKm);

        SSLEngine server = serverCtx.createSSLEngine();
        server.setUseClientMode(false);
        server.setNeedClientAuth(true);

        SSLEngine client = clientCtx.createSSLEngine(
            "wolfSSL ML-DSA test", 11111);
        client.setUseClientMode(true);

        int ret = tf.testConnection(server, client, null,
            new String[] { "TLSv1.3" }, APP_DATA);

        assertEquals("ML-DSA-87 mutual-auth handshake should succeed", 0, ret);
    }

    /**
     * Run server auth handshakes for ML-DSA-44 and ML-DSA-65 too, so we
     * verify all three FIPS 204 parameter sets actually flow through wolfJSSE
     * cert selection and native verification.
     */
    @Test
    public void testServerAuth_MLDSA44_and_65() throws Exception {

        preconditions();
        runServerAuthAtLevel(44);
        runServerAuthAtLevel(65);
    }

    private void runServerAuthAtLevel(int level) throws Exception {

        String serverCert = "examples/certs/pqc/server-mldsa" + level
            + ".pem";
        String serverKey = "examples/certs/pqc/server-mldsa" + level
            + "-priv.pem";
        String rootCert = "examples/certs/pqc/root-mldsa" + level
            + ".pem";

        if (!WolfSSLPQCTestUtil.pqcCertExists(serverCert)) {
            return;
        }

        KeyManager[] km = WolfSSLPQCTestUtil.keyManagerFromPem(
            "server-mldsa" + level, serverCert, serverKey, "ML-DSA-" + level);
        TrustManager[] tm = WolfSSLPQCTestUtil.trustManagerFromPem(rootCert);

        SSLContext serverCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            null, km);
        SSLContext clientCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            tm, null);

        SSLEngine server = serverCtx.createSSLEngine();
        server.setUseClientMode(false);
        server.setNeedClientAuth(false);
        SSLEngine client = clientCtx.createSSLEngine(
            "wolfSSL ML-DSA test", 11111);
        client.setUseClientMode(true);

        int ret = tf.testConnection(server, client, null,
            new String[] { "TLSv1.3" }, APP_DATA);

        if (ret != 0) {
            fail("ML-DSA-" + level +
                " server-auth handshake failed, ret=" + ret);
        }
    }

    /**
     * SSLSession.getLocalSupportedSignatureAlgorithms() must advertise the
     * three ML-DSA parameter set names registered by JEP 497 when native
     * wolfSSL has ML-DSA enabled.
     */
    @Test
    public void testLocalSupportedSignatureAlgorithms_includesMLDSA()
        throws Exception {

        Assume.assumeTrue("ML-DSA not enabled in native wolfSSL",
            WolfSSL.MLDSAEnabled());
        Assume.assumeTrue("TLS 1.3 not enabled in native wolfSSL",
            WolfSSL.TLSv13Enabled());

        SSLContext ctx = tf.createSSLContext("TLSv1.3", PROVIDER);
        SSLEngine engine = ctx.createSSLEngine();
        engine.setUseClientMode(true);

        SSLSession session = engine.getSession();
        Assume.assumeTrue("SSLSession is not an ExtendedSSLSession; " +
            "cannot query getLocalSupportedSignatureAlgorithms",
            session instanceof ExtendedSSLSession);
        String[] sigAlgs = ((ExtendedSSLSession) session)
            .getLocalSupportedSignatureAlgorithms();

        List<String> list = Arrays.asList(sigAlgs);
        assertTrue("getLocalSupportedSignatureAlgorithms() must include " +
            "ML-DSA-44 when native ML-DSA is enabled, got: " + list,
            list.contains("ML-DSA-44"));
        assertTrue("getLocalSupportedSignatureAlgorithms() must include " +
            "ML-DSA-65 when native ML-DSA is enabled, got: " + list,
            list.contains("ML-DSA-65"));
        assertTrue("getLocalSupportedSignatureAlgorithms() must include " +
            "ML-DSA-87 when native ML-DSA is enabled, got: " + list,
            list.contains("ML-DSA-87"));
    }

    /**
     * WolfSSLUtil.formatSigSchemes() must not silently drop ML-DSA scheme
     * names from jdk.tls.{client,server}.SignatureSchemes input. The
     * standalone branch (no hash component, parallel to ED25519/ED448)
     * recognizes the IETF MLDSA{44,65,87} scheme names and emits the
     * canonical FIPS 204 form (ML-DSA-N) into the colon-list passed to
     * native wolfSSL_set1_sigalgs_list().
     *
     * Reflection-based invocation since formatSigSchemes is package-private.
     */
    @Test
    public void testFormatSigSchemes_acceptsMLDSAStandalones()
        throws Exception {

        java.lang.reflect.Method m = com.wolfssl.provider.jsse.WolfSSLUtil
            .class.getDeclaredMethod("formatSigSchemes",
                String.class, String.class);
        m.setAccessible(true);

        String result = (String) m.invoke(null, null,
            "mldsa44,mldsa65,mldsa87");
        assertNotNull("formatSigSchemes must not return null when ML-DSA " +
            "schemes are the only input", result);

        List<String> tokens = Arrays.asList(result.split(":"));
        assertTrue("Output must include ML-DSA-44 when input has mldsa44, " +
            "got: " + result, tokens.contains("ML-DSA-44"));
        assertTrue("Output must include ML-DSA-65 when input has mldsa65, " +
            "got: " + result, tokens.contains("ML-DSA-65"));
        assertTrue("Output must include ML-DSA-87 when input has mldsa87, " +
            "got: " + result, tokens.contains("ML-DSA-87"));
    }

    /**
     * WolfSSLX509.getPublicKey() must not throw for ML-DSA certificates.
     * The native pubkey-type JNI switch returns the JDK 24 / JEP 497
     * family name "ML-DSA" and getPublicKey() resolves a KeyFactory for
     * it. When no installed provider offers an ML-DSA KeyFactory the
     * method returns null, matching its existing behavior when key
     * conversion is not possible, but it must never throw out of the
     * X509Certificate.getPublicKey() API.
     */
    @Test
    public void testWolfSSLX509GetPublicKey_MLDSA() throws Exception {

        Assume.assumeTrue("Native wolfSSL cannot parse ML-DSA certs",
            WolfSSLPQCTestUtil.nativeMlDsaCertParsingSupported());

        String certPath = WolfSSLPQCTestUtil.resolveRepoPath(
            WolfSSLPQCTestUtil.PQC_CERT_DIR + "/server-mldsa44.der");

        WolfSSLX509 cert = new WolfSSLX509(certPath);
        try {
            PublicKey key = cert.getPublicKey();

            boolean kfAvailable = true;
            try {
                KeyFactory.getInstance("ML-DSA");
            } catch (NoSuchAlgorithmException e) {
                kfAvailable = false;
            }

            if (kfAvailable) {
                assertNotNull("getPublicKey() must return a key when an " +
                    "ML-DSA KeyFactory is available", key);
                assertTrue("Public key algorithm should be an ML-DSA " +
                    "name, got: " + key.getAlgorithm(),
                    key.getAlgorithm().contains("ML-DSA"));
            }
            else {
                assertNull("getPublicKey() must return null (not throw) " +
                    "when no ML-DSA KeyFactory is available", key);
            }
        } finally {
            cert.free();
        }
    }

    /**
     * WolfSSLInternalVerifyCb.getAuthTypeFromPeerCert() must derive the
     * authType passed to X509TrustManager checkClientTrusted() /
     * checkServerTrusted() from the peer certificate's public key
     * algorithm, not from the certificate signature algorithm. The
     * signature algorithm is the issuer's algorithm: for a mixed chain
     * (ECC leaf issued by an RSA CA here, or an ML-DSA leaf issued by a
     * classical CA in PQC migration deployments) the two differ.
     *
     * Generates an EC-key certificate signed by the RSA test CA and
     * verifies authType is reported as "ECDSA", where the old
     * signature-based derivation reported "RSA".
     */
    @Test
    public void testGetAuthTypeFromPeerCert_MixedChain() throws Exception {

        Assume.assumeTrue("ECC not compiled into native wolfSSL",
            WolfSSL.EccEnabled());
        Assume.assumeTrue("RSA not compiled into native wolfSSL",
            WolfSSL.RsaEnabled());
        Assume.assumeTrue("No filesystem support in native wolfSSL",
            WolfSSL.FileSystemEnabled());

        String caCertPem = WolfSSLTestCommon.getPath(
            "examples/certs/ca-cert.pem");
        String caKeyDer = WolfSSLTestCommon.getPath(
            "examples/certs/ca-key.der");

        /* EC keypair for the leaf, generated via JCA */
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("EC");
        kpg.initialize(256);
        KeyPair kp = kpg.generateKeyPair();

        WolfSSLCertificate x509 = null;
        WolfSSLCertificate issuer = null;

        try {
            x509 = new WolfSSLCertificate();

            Instant now = Instant.now();
            x509.setNotBefore(Date.from(now));
            x509.setNotAfter(Date.from(now.plus(Duration.ofDays(1))));
            x509.setSerialNumber(BigInteger.valueOf(0xA17C));

            WolfSSLX509Name subject = new WolfSSLX509Name();
            subject.setCommonName("wolfJSSE authType mixed chain test");
            x509.setSubjectName(subject);

            issuer = new WolfSSLCertificate(caCertPem,
                WolfSSL.SSL_FILETYPE_PEM);
            x509.setIssuerName(issuer);
            x509.setPublicKey(kp.getPublic());
            x509.signCert(caKeyDer, WolfSSL.RSAk,
                WolfSSL.SSL_FILETYPE_ASN1, "SHA256");

            /* Fixture sanity: signature is RSA, key is ECC */
            assertTrue("Test cert should be RSA-signed, got: " +
                x509.getSignatureType(),
                x509.getSignatureType().contains("RSA"));

            assertEquals("authType must come from the peer key algorithm " +
                "(ECDSA), not the issuer signature algorithm (RSA)",
                "ECDSA",
                WolfSSLInternalVerifyCb.getAuthTypeFromPeerCert(x509));

        } catch (WolfSSLException e) {
            /* Skip cleanly when native cert generation support
             * (--enable-certgen) is not compiled in */
            String msg = e.getMessage();
            if (msg != null && (msg.contains("NOT_COMPILED_IN") ||
                msg.contains(
                    Integer.toString(WolfSSL.NOT_COMPILED_IN)))) {
                Assume.assumeNoException(e);
            }
            throw e;
        } finally {
            if (issuer != null) {
                issuer.free();
            }
            if (x509 != null) {
                x509.free();
            }
        }
    }

    /**
     * getAuthTypeFromPeerCert() must report "ML-DSA" for an ML-DSA
     * certificate via the native public-key-type path.
     */
    @Test
    public void testGetAuthTypeFromPeerCert_MLDSA() throws Exception {

        Assume.assumeTrue("Native wolfSSL cannot parse ML-DSA certs",
            WolfSSLPQCTestUtil.nativeMlDsaCertParsingSupported());

        String certPath = WolfSSLPQCTestUtil.resolveRepoPath(
            WolfSSLPQCTestUtil.PQC_CERT_DIR + "/server-mldsa44.der");

        WolfSSLCertificate cert = new WolfSSLCertificate(certPath,
            WolfSSL.SSL_FILETYPE_ASN1);
        try {
            assertEquals("authType for an ML-DSA certificate must be " +
                "ML-DSA", "ML-DSA",
                WolfSSLInternalVerifyCb.getAuthTypeFromPeerCert(cert));
        } finally {
            cert.free();
        }
    }

    /**
     * getAuthTypeFromPeerCert() must keep reporting "RSA" for plain RSA
     * certificates (key and signature both RSA).
     */
    @Test
    public void testGetAuthTypeFromPeerCert_RSA() throws Exception {

        Assume.assumeTrue("RSA not compiled into native wolfSSL",
            WolfSSL.RsaEnabled());
        Assume.assumeTrue("No filesystem support in native wolfSSL",
            WolfSSL.FileSystemEnabled());

        String caCertPem = WolfSSLTestCommon.getPath(
            "examples/certs/ca-cert.pem");

        WolfSSLCertificate cert = new WolfSSLCertificate(caCertPem,
            WolfSSL.SSL_FILETYPE_PEM);
        try {
            assertEquals("authType for an RSA certificate must be RSA",
                "RSA",
                WolfSSLInternalVerifyCb.getAuthTypeFromPeerCert(cert));
        } finally {
            cert.free();
        }
    }
}
