/* WolfSSLPQCAuthJksTest.java
 *
 * Copyright (C) 2006-2026 wolfSSL Inc.
 *
 * This file is part of wolfSSL.
 *
 * wolfSSL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * wolfSSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

package com.wolfssl.provider.jsse.test;

import com.wolfssl.WolfSSL;
import com.wolfssl.provider.jsse.WolfSSLProvider;
import com.wolfssl.test.TimedTestWatcher;
import java.io.File;
import java.io.FileInputStream;
import java.security.KeyFactory;
import java.security.KeyStore;
import java.security.NoSuchAlgorithmException;
import java.security.Security;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.TrustManagerFactory;
import org.junit.Assume;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestRule;
import static org.junit.Assert.assertEquals;

/**
 * ML-DSA cert authentication tests via standard JCE KeyStore (JKS).
 *
 * Exercises the standard Java security stack that a typical JDK 24+
 * application would use:
 *   - KeyStore.getInstance("JKS") to load JKS with ML-DSA private key + cert
 *   - KeyManagerFactory / TrustManagerFactory through wolfJSSE
 *   - Standard SSLContext.init()
 *
 * Skipped on JDK less than 24: ML-DSA KeyFactory was added in JEP 497 (JDK 24).
 * Older JDKs cannot load ML-DSA private keys from a standard JKS, but the JKS
 * *files* themselves are harmless to ship. They're only opened when this test
 * runs.
 *
 * The JKS test fixtures (server-mldsa{44,65,87}.jks + ca-mldsa{44,65,87}.jks
 * under examples/provider/) are produced by examples/provider/update-jks-pqc.sh
 * which itself requires JDK 24+.
 *
 * For coverage on older JDKs (or when not relying on JKS at all),
 * see {@link WolfSSLPQCAuthenticationTest}, which loads PEM keys generated by
 * OpenSSL through a custom KeyManager.
 */
public class WolfSSLPQCAuthJksTest {

    private static final String PROVIDER = "wolfJSSE";
    private static final String APP_DATA = "PQC JKS test";
    private static final char[] JKS_PASS = "wolfSSL test".toCharArray();

    private static WolfSSLTestFactory tf;
    private static boolean jdkHasMlDsa = false;

    @Rule
    public TestRule testWatcher = TimedTestWatcher.create();

    @BeforeClass
    public static void setUp() throws Exception {

        System.out.println("WolfSSLPQCAuthJks Class");

        Security.insertProviderAt(new WolfSSLProvider(), 1);
        tf = new WolfSSLTestFactory();

        /* Probe for ML-DSA KeyFactory (JEP 497, JDK 24+). Cached for lifetime
         * of the test class so all @Test methods can do a cheap check. */
        try {
            KeyFactory.getInstance("ML-DSA");
            jdkHasMlDsa = true;
        } catch (NoSuchAlgorithmException e) {
            jdkHasMlDsa = false;
        }
    }

    /**
     * Shared per-test precondition check. Routes through Assume so the
     * TimedTestWatcher reports SKIP rather than the test failing.
     */
    private void preconditions(String jksFilename) {

        Assume.assumeTrue(WolfSSL.MLDSAEnabled() && WolfSSL.TLSv13Enabled());
        Assume.assumeTrue("JDK < 24, no JCE ML-DSA KeyFactory", jdkHasMlDsa);
        Assume.assumeTrue(
            "JKS missing; run examples/provider/update-jks-pqc.sh first",
            new File("examples/provider/" + jksFilename).isFile());
    }

    private void runJksHandshake(int level) throws Exception {

        String serverJksPath = "examples/provider/server-mldsa"
            + level + ".jks";
        String caJksPath = "examples/provider/ca-mldsa" + level + ".jks";

        /* Server keystore: private key + CA-signed cert chain. */
        KeyStore serverKs = KeyStore.getInstance("JKS");
        FileInputStream in = new FileInputStream(serverJksPath);
        try {
            serverKs.load(in, JKS_PASS);
        } finally {
            in.close();
        }
        KeyManagerFactory kmf =
            KeyManagerFactory.getInstance("SunX509", PROVIDER);
        kmf.init(serverKs, JKS_PASS);

        /* Client truststore: just the root CA cert (no private key). */
        KeyStore caKs = KeyStore.getInstance("JKS");
        in = new FileInputStream(caJksPath);
        try {
            caKs.load(in, JKS_PASS);
        } finally {
            in.close();
        }
        TrustManagerFactory tmf =
            TrustManagerFactory.getInstance("SunX509", PROVIDER);
        tmf.init(caKs);

        SSLContext serverCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            null, kmf.getKeyManagers());
        SSLContext clientCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            tmf.getTrustManagers(), null);

        SSLEngine server = serverCtx.createSSLEngine();
        server.setUseClientMode(false);
        server.setNeedClientAuth(false);

        SSLEngine client = clientCtx.createSSLEngine(
            "wolfSSL JKS PQC test", 11111);
        client.setUseClientMode(true);

        int ret = tf.testConnection(server, client, null,
            new String[] { "TLSv1.3" }, APP_DATA);
        assertEquals("ML-DSA-" + level + " JKS handshake should succeed",
            0, ret);
    }

    @Test
    public void testJksServerAuth_MLDSA44() throws Exception {
        preconditions("server-mldsa44.jks");
        runJksHandshake(44);
    }

    @Test
    public void testJksServerAuth_MLDSA65() throws Exception {
        preconditions("server-mldsa65.jks");
        runJksHandshake(65);
    }

    @Test
    public void testJksServerAuth_MLDSA87() throws Exception {
        preconditions("server-mldsa87.jks");
        runJksHandshake(87);
    }
}
