/* WolfSSLPQCAuthenticationTest.java
 *
 * Copyright (C) 2006-2026 wolfSSL Inc.
 *
 * This file is part of wolfSSL.
 *
 * wolfSSL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * wolfSSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335, USA
 */

package com.wolfssl.provider.jsse.test;

import com.wolfssl.WolfSSL;
import com.wolfssl.WolfSSLException;
import com.wolfssl.provider.jsse.WolfSSLProvider;
import com.wolfssl.test.TimedTestWatcher;
import java.security.NoSuchProviderException;
import java.security.Security;
import javax.net.ssl.KeyManager;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.TrustManager;
import org.junit.Assume;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestRule;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

/**
 * Integration tests for ML-DSA (FIPS 204) X.509 cert authentication via
 * wolfJSSE TLS 1.3.
 *
 * Uses {@link WolfSSLPQCTestUtil}'s custom KeyManager helper, which loads PEM
 * certs and PKCS#8 DER keys directly without invoking JCE KeyFactory. This
 * makes the same test runnable on Java 8 (no ML-DSA in JEP 497) through
 * JDK 24+ alike. Cert verification is delegated to native wolfSSL via wolfJSSE.
 *
 * Skipped automatically when:
 *   - native wolfSSL was not built with --enable-mldsa, OR
 *   - TLS 1.3 is not compiled in, OR
 *   - the gen-mldsa-certs.sh script has not been run (no PQC PEM files
 *     under examples/certs/pqc/).
 */
public class WolfSSLPQCAuthenticationTest {

    private static final String PROVIDER = "wolfJSSE";
    private static final String APP_DATA = "PQC auth test";

    /* ML-DSA-87 (CNSA 2.0) cert paths.
     * Generated by examples/certs/gen-mldsa-certs.sh */
    private static final String SERVER_CERT =
        "examples/certs/pqc/server-mldsa87.pem";
    private static final String SERVER_KEY =
        "examples/certs/pqc/server-mldsa87-priv.pem";
    private static final String CLIENT_CERT =
        "examples/certs/pqc/client-mldsa87.pem";
    private static final String CLIENT_KEY =
        "examples/certs/pqc/client-mldsa87-priv.pem";
    private static final String ROOT_CERT =
        "examples/certs/pqc/root-mldsa87.pem";

    private static WolfSSLTestFactory tf;

    @Rule
    public TestRule testWatcher = TimedTestWatcher.create();

    @BeforeClass
    public static void setUp()
        throws NoSuchProviderException, WolfSSLException {

        System.out.println("WolfSSLPQCAuthentication Class");

        Security.insertProviderAt(new WolfSSLProvider(), 1);
        tf = new WolfSSLTestFactory();
    }

    /**
     * Common skip preconditions for every test in this class. Routes
     * through Assume so the TimedTestWatcher reports SKIP rather than
     * the test failing.
     */
    private void preconditions() {
        Assume.assumeTrue(WolfSSL.MLDSAEnabled() && WolfSSL.TLSv13Enabled());
        Assume.assumeTrue(
            "PQC cert PEM missing; run gen-mldsa-certs.sh first",
            WolfSSLPQCTestUtil.pqcCertExists(ROOT_CERT));
    }

    /**
     * Server presents an ML-DSA-87 cert. Client trusts the matching root and
     * verifies. No client auth.
     */
    @Test
    public void testServerAuth_MLDSA87() throws Exception {

        preconditions();

        KeyManager[] serverKm = WolfSSLPQCTestUtil.keyManagerFromPem(
            "server-mldsa87", SERVER_CERT, SERVER_KEY, "ML-DSA-87");
        TrustManager[] clientTm =
            WolfSSLPQCTestUtil.trustManagerFromPem(ROOT_CERT);

        SSLContext serverCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            null, serverKm);
        SSLContext clientCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            clientTm, null);

        SSLEngine server = serverCtx.createSSLEngine();
        server.setUseClientMode(false);
        server.setNeedClientAuth(false);

        SSLEngine client = clientCtx.createSSLEngine(
            "wolfSSL ML-DSA test", 11111);
        client.setUseClientMode(true);

        int ret = tf.testConnection(server, client, null,
            new String[] { "TLSv1.3" }, APP_DATA);

        assertEquals("ML-DSA-87 server-auth handshake should succeed", 0, ret);
    }

    /**
     * Mutual auth: both server and client present ML-DSA-87 certs, each side
     * trusts the matching root.
     */
    @Test
    public void testMutualAuth_MLDSA87() throws Exception {

        preconditions();

        KeyManager[] serverKm = WolfSSLPQCTestUtil.keyManagerFromPem(
            "server-mldsa87", SERVER_CERT, SERVER_KEY, "ML-DSA-87");
        TrustManager[] serverTm =
            WolfSSLPQCTestUtil.trustManagerFromPem(ROOT_CERT);
        KeyManager[] clientKm = WolfSSLPQCTestUtil.keyManagerFromPem(
            "client-mldsa87", CLIENT_CERT, CLIENT_KEY, "ML-DSA-87");
        TrustManager[] clientTm =
            WolfSSLPQCTestUtil.trustManagerFromPem(ROOT_CERT);

        SSLContext serverCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            serverTm, serverKm);
        SSLContext clientCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            clientTm, clientKm);

        SSLEngine server = serverCtx.createSSLEngine();
        server.setUseClientMode(false);
        server.setNeedClientAuth(true);

        SSLEngine client = clientCtx.createSSLEngine(
            "wolfSSL ML-DSA test", 11111);
        client.setUseClientMode(true);

        int ret = tf.testConnection(server, client, null,
            new String[] { "TLSv1.3" }, APP_DATA);

        assertEquals("ML-DSA-87 mutual-auth handshake should succeed", 0, ret);
    }

    /**
     * Run server auth handshakes for ML-DSA-44 and ML-DSA-65 too, so we
     * verify all three FIPS 204 parameter sets actually flow through wolfJSSE
     * cert selection and native verification.
     */
    @Test
    public void testServerAuth_MLDSA44_and_65() throws Exception {

        preconditions();
        runServerAuthAtLevel(44);
        runServerAuthAtLevel(65);
    }

    private void runServerAuthAtLevel(int level) throws Exception {

        String serverCert = "examples/certs/pqc/server-mldsa" + level
            + ".pem";
        String serverKey = "examples/certs/pqc/server-mldsa" + level
            + "-priv.pem";
        String rootCert = "examples/certs/pqc/root-mldsa" + level
            + ".pem";

        if (!WolfSSLPQCTestUtil.pqcCertExists(serverCert)) {
            return;
        }

        KeyManager[] km = WolfSSLPQCTestUtil.keyManagerFromPem(
            "server-mldsa" + level, serverCert, serverKey, "ML-DSA-" + level);
        TrustManager[] tm = WolfSSLPQCTestUtil.trustManagerFromPem(rootCert);

        SSLContext serverCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            null, km);
        SSLContext clientCtx = tf.createSSLContext("TLSv1.3", PROVIDER,
            tm, null);

        SSLEngine server = serverCtx.createSSLEngine();
        server.setUseClientMode(false);
        server.setNeedClientAuth(false);
        SSLEngine client = clientCtx.createSSLEngine(
            "wolfSSL ML-DSA test", 11111);
        client.setUseClientMode(true);

        int ret = tf.testConnection(server, client, null,
            new String[] { "TLSv1.3" }, APP_DATA);

        if (ret != 0) {
            fail("ML-DSA-" + level +
                " server-auth handshake failed, ret=" + ret);
        }
    }
}
