name: Linux Java 8 Tests

on:
  workflow_call:

jobs:
  build_wolfssl:
    name: Build wolfSSL
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Build wolfSSL
        uses: wolfSSL/actions-build-autotools-project@v1
        with:
          path: wolfssl
          configure: --enable-jni
          install: true

  build_wolfssljni:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add more distributions to matrix here
        distribution: [ 'zulu' ]
        java: [ '8' ]
    name: Ubuntu ${{ matrix.java }} (${{ matrix.distribution }})
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Build JNI library
        run: ./java.sh
      - name: ant
        run: ant
      - name: ant test
        run: ant test
      - name: Show logs on failure
        if: failure() || cancelled()
        run: |
          cat build/reports/*.txt
